### ISSUE TITLE
List names of message attachments

### ISSUE THREAD

**Issue by jwhugheskp** [janscas/py-o365#17]
Hi Alejandro,

I've been poking at the pyo365 code and I still don't see how I can list the message attachment names.    I haven't figured out how you count the number of attachments and then list the attachment names.  Is there a method or property that I'm missing?

TIA,
Joe

**Comment by alejcas** [comment]
Hi!
The message attachments are not retrieved by default when you ask for messages. If you want to have the attachments downloaded as well, then you have to pass True to `download_attachments` parameter on `get_message`or `get_messages` in any `Folder` instance.

However, note that at this moment, the download_attachments option is very inefficient because it will make an additional request for every message retrieved. So if you retrieve 100 messages (and all have attachments) it will make 101 requests.

This will change on the future with some improvements I have in mind.

For the moment it's better to ask for the messages you want, then check the property `has_attachments` and if True call `message.attachments.download_attachments()`.

Hope this helps

**Comment by jwhugheskp** [comment]
Hi Alejandro,

I have this code

        if message.has_attachments:
            print("Has Attachments:", message.has_attachments)
            print(message.attachments.download_attachments())

What I'm trying to do is just list the attachments.  What I get from the second print is "True"   I assume I'm still missing something.  Also the list question applies to the to, cc, and bcc list.  I'm getting numbers, but what I need is the mail addresses in each list.  We are trying to take data from a spam mailbox and run it into a SIEM.

TIA,
Joe

**Comment by alejcas** [comment]
Let the python magic begin:

```python
if message.has_attachments:
    message.download_attachments()
    for attachment in message.attachments:
        attachment.save()  # save to the local disk or whatever you want to do.
```

**Comment by jwhugheskp** [comment]
Hi Alejandro,

I have this code now

        if message.has_attachments:
            print("Attachments:", message.has_attachments)
            message.download_attachments()

            for attachment in message.attachments:
                print(attachment.save())

I get this error

Attachments: True
Traceback (most recent call last):
  File "get_mail.py", line 98, in <module>
    main()
  File "get_mail.py", line 90, in main
    print_email()    
  File "get_mail.py", line 68, in print_email
    message.download_attachments()
AttributeError: 'Message' object has no attribute 'download_attachments'

TIA,
Joe

**Comment by alejcas** [comment]
I'm sorry! My fault!

It's: `message.attachments.download_attachments()`
